-- Reading Age / Genre / Sub Genre / Mood facets
-- (replaces category, sub-categories, and tags as the book classification).
alter table books
  add column if not exists reading_age text,
  add column if not exists genre text,
  add column if not exists sub_genre text,
  add column if not exists mood text;

-- Import the values from the CSV, matched by title.
update books b set
  reading_age = v.reading_age,
  genre = v.genre,
  sub_genre = v.sub_genre,
  mood = v.mood
from (values
  ('100 Cookies', 'Adult', 'Cookbook', 'Baking', 'Light & Fun'),
  ('3 Doughs, 60 Recipes: Sandwich Bread, Focaccia, Pizza – Easy-To-Master Doughs and Delicious Ways to Enjoy Them', 'Adult', 'Cookbook', 'Baking', 'Light & Fun'),
  ('A Conjuring of Light', 'Adult', 'Fantasy', 'Urban Fantasy', 'Compulsive / Unputdownable'),
  ('A Darker Shade of Magic', 'Adult', 'Fantasy', 'Urban Fantasy', 'Compulsive / Unputdownable'),
  ('A Gathering of Shadows', 'Adult', 'Fantasy', 'Urban Fantasy', 'Compulsive / Unputdownable'),
  ('A Language of Dragons', 'Adult', 'Fantasy', 'Epic Fantasy', 'Atmospheric & Immersive'),
  ('A Sorceress Comes to Call', 'Adult', 'Fantasy', 'Folk & Fairy Tale', 'Dark & Intense'),
  ('Alchemised', 'Adult', 'Fantasy', 'Romantic Fantasy', 'Emotionally Devastating'),
  ('Atomic Habits', 'Adult', 'Non-Fiction', 'Psychology', 'Thought Provoking'),
  ('Babel Indigo Special Edition: A Novel', 'Adult', 'Fantasy', 'Dark Academia', 'Atmospheric & Immersive'),
  ('Bake It Better: 70 Show-Stopping Recipes to Level Up Your Baking Skills', 'Adult', 'Cookbook', 'Baking', 'Light & Fun'),
  ('Blood Over Bright Haven', 'Adult', 'Fantasy', 'Dark Academia', 'Compulsive / Unputdownable'),
  ('Carl''s Doomsday Scenario', 'Adult', 'Sci-Fi', 'Dystopian', 'Compulsive / Unputdownable'),
  ('Clockwork Boys', 'Adult', 'Fantasy', 'Epic Fantasy', 'Compulsive / Unputdownable'),
  ('Crumbs and Doilies', 'Adult', 'Cookbook', 'Baking', 'Light & Fun'),
  ('Dungeon Crawler Carl', 'Adult', 'Sci-Fi', 'Dystopian', 'Compulsive / Unputdownable'),
  ('Empire of Storms', 'Adult', 'Fantasy', 'Epic Fantasy', 'Compulsive / Unputdownable'),
  ('Everyday Comfort Food', 'Adult', 'Cookbook', 'General', 'Light & Fun'),
  ('Fourth Wing', 'Adult', 'Fantasy', 'Romantic Fantasy', 'Compulsive / Unputdownable'),
  ('From Blood and Ash', 'Adult', 'Fantasy', 'Romantic Fantasy', 'Compulsive / Unputdownable'),
  ('Gild: The Dark Fantasy Romance TikTok Sensation That’s Sold Over a Million Copies', 'Adult', 'Fantasy', 'Romantic Fantasy', 'Dark & Intense'),
  ('Glow: The Dark Fantasy Romance TikTok Sensation That’s Sold Over a Million Copies', 'Adult', 'Fantasy', 'Romantic Fantasy', 'Dark & Intense'),
  ('Gravity Let Me Go', 'Adult', 'Contemporary Fiction', 'Slice of Life', 'Emotionally Devastating'),
  ('Home Baked', 'Adult', 'Cookbook', 'Baking', 'Light & Fun'),
  ('Just a Mum''s Kitchen', 'Adult', 'Cookbook', 'General', 'Light & Fun'),
  ('Kingdom of Ash', 'Adult', 'Fantasy', 'Epic Fantasy', 'Emotionally Devastating'),
  ('La Belle Sauvage: The Book of Dust Volume One', 'Adult', 'Fantasy', 'Epic Fantasy', 'Atmospheric & Immersive'),
  ('Last-Minute Knitted Gifts', 'Adult', 'Non-Fiction', 'Craft', 'Light & Fun'),
  ('Lazy Baking: Really Easy Sweet and Savoury Bakes', 'Adult', 'Cookbook', 'Baking', 'Light & Fun'),
  ('Lightlark (The Lightlark Saga Book 1)', 'YA', 'Fantasy', 'Romantic Fantasy', 'Compulsive / Unputdownable'),
  ('Milk Bar Life', 'Adult', 'Cookbook', 'Baking', 'Light & Fun'),
  ('Nettle & Bone', 'Adult', 'Fantasy', 'Folk & Fairy Tale', 'Dark & Intense'),
  ('Nourish', 'Adult', 'Cookbook', 'General', 'Light & Fun'),
  ('Oakleaf Bearers', '9+', 'Fantasy', 'Epic Fantasy', 'Compulsive / Unputdownable'),
  ('On Wings of Blood (Bloodwing Academy, Book 1)', 'Adult', 'Fantasy', 'Romantic Fantasy', 'Compulsive / Unputdownable'),
  ('One Dark Window', 'Adult', 'Fantasy', 'Gothic', 'Atmospheric & Immersive'),
  ('Paladin''s Faith', 'Adult', 'Fantasy', 'Romantic Fantasy', 'Compulsive / Unputdownable'),
  ('Paladin''s Grace', 'Adult', 'Fantasy', 'Romantic Fantasy', 'Cosy & Warm'),
  ('Paladin''s Hope', 'Adult', 'Fantasy', 'Romantic Fantasy', 'Cosy & Warm'),
  ('Percy Jackson and the Titan''s Curse', '9+', 'Fantasy', 'Mythology', 'Compulsive / Unputdownable'),
  ('Project Hail Mary', 'Adult', 'Sci-Fi', 'General', 'Compulsive / Unputdownable'),
  ('Remarkably Bright Creatures', 'Adult', 'Contemporary Fiction', 'Slice of Life', 'Cosy & Warm'),
  ('Remarkably Bright Creatures: ''That Octopus Book'', the Major Bestseller Coming to Netflix Soon', 'Adult', 'Contemporary Fiction', 'Slice of Life', 'Cosy & Warm'),
  ('Salt, Fat, Acid, Heat: Mastering the Elements of Good Cooking', 'Adult', 'Cookbook', 'General', 'Thought Provoking'),
  ('Shield of Sparrows: THE INSTANT SUNDAY TIMES AND NEW YORK TIMES BESTSELLER', 'Adult', 'Fantasy', 'Romantic Fantasy', 'Compulsive / Unputdownable'),
  ('SIFT: The Food Book of the Year – Times & Sunday Times', 'Adult', 'Cookbook', 'Baking', 'Thought Provoking'),
  ('Skipshock', 'YA', 'Sci-Fi', 'Romantic Fantasy', 'Atmospheric & Immersive'),
  ('Summer Favourites', 'Adult', 'Cookbook', 'General', 'Light & Fun'),
  ('The Anxious Generation: How the Great Rewiring of Childhood Is Causing an Epidemic of Mental Illness', 'Adult', 'Non-Fiction', 'Psychology', 'Thought Provoking'),
  ('The Assassin’s Blade', 'Adult', 'Fantasy', 'Epic Fantasy', 'Compulsive / Unputdownable'),
  ('The Battle of the Labyrinth', '9+', 'Fantasy', 'Mythology', 'Compulsive / Unputdownable'),
  ('The Book of Dust: Volume Two', 'Adult', 'Fantasy', 'Epic Fantasy', 'Atmospheric & Immersive'),
  ('The Bookshop Detectives: Dead Girl Gone', 'Adult', 'Thriller & Mystery', 'Cosy Mystery', 'Light & Fun'),
  ('The Bullet That Missed', 'Adult', 'Thriller & Mystery', 'Cosy Mystery', 'Light & Fun'),
  ('The Burning Bridge', '9+', 'Fantasy', 'Epic Fantasy', 'Compulsive / Unputdownable'),
  ('The Butcher''s Masquerade', 'Adult', 'Sci-Fi', 'Dystopian', 'Compulsive / Unputdownable'),
  ('The Chalice of the Gods', '9+', 'Fantasy', 'Mythology', 'Compulsive / Unputdownable'),
  ('The Crimson Moth (The Crimson Moth, Book 1)', 'Adult', 'Fantasy', 'Romantic Fantasy', 'Compulsive / Unputdownable'),
  ('The Cruel Prince', 'YA', 'Fantasy', 'Folk & Fairy Tale', 'Dark & Intense'),
  ('The Dungeon Anarchist''s Cookbook', 'Adult', 'Sci-Fi', 'Dystopian', 'Compulsive / Unputdownable'),
  ('The Eye of the Bedlam Bride', 'Adult', 'Sci-Fi', 'Dystopian', 'Compulsive / Unputdownable'),
  ('The Frozen River: From the Bestselling Author of Code Name Hélène', 'Adult', 'Historical Fiction', 'Historical Mystery', 'Atmospheric & Immersive'),
  ('The Games Gods Play', 'Adult', 'Fantasy', 'Romantic Fantasy', 'Compulsive / Unputdownable'),
  ('The Games Gods Play: The Spicy New Romantasy Epic for Lovers of Fourth Wing and a Court of Thorns and Roses', 'Adult', 'Fantasy', 'Romantic Fantasy', 'Compulsive / Unputdownable'),
  ('The Gate of the Feral Gods', 'Adult', 'Sci-Fi', 'Dystopian', 'Compulsive / Unputdownable'),
  ('The Hollow Places', 'Adult', 'Horror', 'Gothic', 'Dark & Intense'),
  ('The House in the Cerulean Sea', 'Adult', 'Fantasy', 'Cosy & Warm', 'Cosy & Warm'),
  ('The Hungry Cook', 'Adult', 'Cookbook', 'General', 'Light & Fun'),
  ('The Icebound Land', '9+', 'Fantasy', 'Epic Fantasy', 'Compulsive / Unputdownable'),
  ('The Invisible Life of Addie LaRue', 'Adult', 'Fantasy', 'Romantic Fantasy', 'Emotionally Devastating'),
  ('The Kristin Hannah Collection: Volume 2: Winter Garden, Night Road, Home Front', 'Adult', 'Contemporary Fiction', 'Slice of Life', 'Emotionally Devastating'),
  ('The Last Devil To Die', 'Adult', 'Thriller & Mystery', 'Cosy Mystery', 'Light & Fun'),
  ('The Librarian of Crooked Lane: A Fantasy Mystery Novel', 'Adult', 'Thriller & Mystery', 'Historical Mystery', 'Atmospheric & Immersive'),
  ('The Lightning Thief', '9+', 'Fantasy', 'Mythology', 'Compulsive / Unputdownable'),
  ('The Locked Door', 'Adult', 'Thriller & Mystery', 'Psychological', 'Dark & Intense'),
  ('The Lost Bookshop', 'Adult', 'Contemporary Fiction', 'Magical Realism', 'Cosy & Warm'),
  ('The Mysterious Bakery on Rue De Paris', 'Adult', 'Contemporary Fiction', 'Magical Realism', 'Cosy & Warm'),
  ('The New Menopause', 'Adult', 'Non-Fiction', 'Health & Wellbeing', 'Thought Provoking'),
  ('The New Menopause: Navigating Your Path Through Hormonal Change With Purpose, Power and the Facts', 'Adult', 'Non-Fiction', 'Health & Wellbeing', 'Thought Provoking'),
  ('The No-Nonsense Meditation Book: A Scientist''s Guide to the Power of Meditation', 'Adult', 'Non-Fiction', 'Health & Wellbeing', 'Thought Provoking'),
  ('The Queen of Nothing', 'YA', 'Fantasy', 'Folk & Fairy Tale', 'Dark & Intense'),
  ('The Rebel Witch', 'Adult', 'Fantasy', 'Romantic Fantasy', 'Compulsive / Unputdownable'),
  ('The Red Pyramid', '9+', 'Fantasy', 'Mythology', 'Compulsive / Unputdownable'),
  ('The Ruins of Gorlan', '9+', 'Fantasy', 'Epic Fantasy', 'Compulsive / Unputdownable'),
  ('The Serpent''s Shadow', '9+', 'Fantasy', 'Mythology', 'Compulsive / Unputdownable'),
  ('The Sorcerer In the North', '9+', 'Fantasy', 'Epic Fantasy', 'Compulsive / Unputdownable'),
  ('The Spook''s Apprentice', '9+', 'Fantasy', 'Gothic', 'Dark & Intense'),
  ('The Spook''s Curse', '9+', 'Fantasy', 'Gothic', 'Dark & Intense'),
  ('The Spook''s Secret', '9+', 'Fantasy', 'Gothic', 'Dark & Intense'),
  ('The Stolen Queen', 'Adult', 'Historical Fiction', 'Historical Mystery', 'Atmospheric & Immersive'),
  ('The Strength of the Few', 'Adult', 'Fantasy', 'Epic Fantasy', 'Compulsive / Unputdownable'),
  ('The Throne of Fire', '9+', 'Fantasy', 'Mythology', 'Compulsive / Unputdownable'),
  ('The Twisted Ones', 'Adult', 'Horror', 'Gothic', 'Dark & Intense'),
  ('The Ultimate Meal Planning for One', 'Adult', 'Cookbook', 'General', 'Light & Fun'),
  ('The Wicked King', 'YA', 'Fantasy', 'Folk & Fairy Tale', 'Dark & Intense'),
  ('There Are Rivers in the Sky: The Beautiful Sunday Times Bestseller From the Author of the Island of Missing Trees & BBC Between the Covers Book Club Pick', 'Adult', 'Literary Fiction', 'Historical', 'Emotionally Devastating'),
  ('This Inevitable Ruin', 'Adult', 'Sci-Fi', 'Dystopian', 'Compulsive / Unputdownable'),
  ('Tomorrow, and Tomorrow, and Tomorrow', 'Adult', 'Contemporary Fiction', 'Slice of Life', 'Emotionally Devastating'),
  ('Tower of Dawn', 'Adult', 'Fantasy', 'Epic Fantasy', 'Compulsive / Unputdownable'),
  ('Two Twisted Crowns', 'Adult', 'Fantasy', 'Gothic', 'Atmospheric & Immersive'),
  ('What Moves the Dead', 'Adult', 'Horror', 'Gothic', 'Atmospheric & Immersive'),
  ('What Stalks the Deep', 'Adult', 'Horror', 'Gothic', 'Atmospheric & Immersive'),
  ('Why Has Nobody Told Me This Before?: The Sunday Times Bestseller, With Over 1 Million Copies Sold', 'Adult', 'Non-Fiction', 'Health & Wellbeing', 'Thought Provoking'),
  ('Wild Reverence', 'Adult', 'Fantasy', 'Romantic Fantasy', 'Atmospheric & Immersive'),
  ('Wolf in White Van', 'Adult', 'Literary Fiction', 'Psychological', 'Thought Provoking'),
  ('Wrath of the Triple Goddess', '9+', 'Fantasy', 'Mythology', 'Compulsive / Unputdownable'),
  ('Yellowface', 'Adult', 'Contemporary Fiction', 'Slice of Life', 'Dark & Intense')
) as v(title, reading_age, genre, sub_genre, mood)
where b.title = v.title;

-- Retire the old classification.
update books set tags = '{}', subcategories = '{}', category = null;

notify pgrst, 'reload schema';
